name: GitHub-Profile-Summary-Cards

on:
  schedule: # execute every 24 hours
    - cron: "* */24 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate

    steps:
      - uses: actions/checkout@v2
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          50a93c942725e22ee6ae08a2b01592ed3bacf6f3: ${{ secrets.GITHUB_TOKEN }}
        with:
          KKe-coder: ${{ github.repository_owner }}
